/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacionelectronica;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Jaime
 */
public class xmlRetencion2 {
    String ambiente = "";
    String tipoEmision = "1";
    String razonSocial = "";
    String nombreComercial = "";
    String ruc = "";
    String claveAcceso = "";
    String codDoc = "";
    String establecimiento="";
    String puntoEmision="";
    String secuencial="";
    String Matriz="";
    
    String Fecha="";
    String Direccion="";
    String contribEsp="";
    String obligCont="";
    String cliTipId="";
    String cliRazonSocial="";
    String cliId="";
    String cliPerFiscal="";
    
    String adicional1 = "";
    String adicional2 = "";
    String adicional3 = "";
    String impuestos = "";
    
//    List<detalle> det = new ArrayList<>();

    public String generarXML(){
        String xml;
        xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<!--Sample XML file generated by XMLSPY v5 rel. 3 U (http://www.xmlspy.com)-->\n" +
            "<comprobanteRetencion xmlns:ns1=\"http://www.w3.org/2000/09/xmldsig#\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"C:\\Documents and Settings\\mfsalazar\\Escritorio\\facturación electronica\\formato xsd xml 07-03\\comprobanteRetencion1.xsd\" id=\"comprobante\" version=\"NMTOKEN\">\n" +
            "	<infoTributaria>\n" +
            "		<ambiente>"+ambiente+"</ambiente>\n" +
            "		<tipoEmision>1</tipoEmision>\n" +
            "		<razonSocial>"+razonSocial+"</razonSocial>\n" +
            "		<nombreComercial>"+razonSocial+"</nombreComercial>\n" +
            "		<ruc>"+ruc+"</ruc>\n" +
            "		<claveAcceso>"+claveAcceso+"</claveAcceso>\n" +
            "		<codDoc>"+codDoc+"</codDoc>\n" +
            "		<estab>"+establecimiento+"</estab>\n" +
            "		<ptoEmi>"+puntoEmision+"</ptoEmi>\n" +
            "		<secuencial>"+secuencial+"</secuencial>\n" +
            "		<dirMatriz>"+Matriz+"</dirMatriz>\n" +
            "	</infoTributaria>\n" +
            "	<infoCompRetencion>\n" +
            "		<fechaEmision>"+Fecha+"</fechaEmision>\n" +
            "		<dirEstablecimiento>"+establecimiento+"</dirEstablecimiento>\n" +
            "		<contribuyenteEspecial>"+contribEsp+"</contribuyenteEspecial>\n" +
            "		<obligadoContabilidad>"+obligCont+"</obligadoContabilidad>\n" +
            "		<tipoIdentificacionSujetoRetenido>"+cliTipId+"</tipoIdentificacionSujetoRetenido>\n" +
            "		<razonSocialSujetoRetenido>"+cliRazonSocial+"</razonSocialSujetoRetenido>\n" +
            "		<identificacionSujetoRetenido>"+cliId+"</identificacionSujetoRetenido>\n" +
            "		<periodoFiscal>"+cliPerFiscal+"</periodoFiscal>\n" +
            "	</infoCompRetencion>\n" +
            "	<impuestos>\n" +
            impuestos+
            "	</impuestos>\n" +
            "	<infoAdicional>\n" +
            "		<campoAdicional nombre=\""+"\">Ax</campoAdicional>\n" +
            "		<campoAdicional nombre=\""+"\">Ax</campoAdicional>\n" +
            "		<campoAdicional nombre=\""+"\">Ax</campoAdicional>\n" +
            "	</infoAdicional>\n" +
            "</comprobanteRetencion>";
        return xml;
    }
    
    public static class detalle{
        String impCod="";
        String impCodRet="";
        String impBaseImp="";
        String impPorcentaje="";
        String impValorRet="";
        String impCodDocSus="";
        String impNumDocSus="";
        String impFecDocSus="";
        
        public String getDetalleXml() {
            String xml = ""+
            "		<impuesto>\n" +
            "			<codigo>"+impCod+"</codigo>\n" +
            "			<codigoRetencion>"+impCodRet+"</codigoRetencion>\n" +
            "			<baseImponible>"+impBaseImp+"</baseImponible>\n" +
            "			<porcentajeRetener>"+impPorcentaje+"</porcentajeRetener>\n" +
            "			<valorRetenido>"+impValorRet+"</valorRetenido>\n" +
            "			<codDocSustento>"+impCodDocSus+"</codDocSustento>\n" +
            "			<numDocSustento>"+impNumDocSus+"</numDocSustento>\n" +
            "			<fechaEmisionDocSustento>"+impFecDocSus+"</fechaEmisionDocSustento>\n" +
            "		</impuesto>\n";
            return xml;
        }
        
        public String getImpCod() {
            return impCod;
        }

        public void setImpCod(String impCod) {
            this.impCod = impCod;
        }

        public String getImpCodRet() {
            return impCodRet;
        }

        public void setImpCodRet(String impCodRet) {
            this.impCodRet = impCodRet;
        }

        public String getImpBaseImp() {
            return impBaseImp;
        }

        public void setImpBaseImp(String impBaseImp) {
            this.impBaseImp = impBaseImp;
        }

        public String getImpPorcentaje() {
            return impPorcentaje;
        }

        public void setImpPorcentaje(String impPorcentaje) {
            this.impPorcentaje = impPorcentaje;
        }

        public String getImpValorRet() {
            return impValorRet;
        }

        public void setImpValorRet(String impValorRet) {
            this.impValorRet = impValorRet;
        }

        public String getImpCodDocSus() {
            return impCodDocSus;
        }

        public void setImpCodDocSus(String impCodDocSus) {
            this.impCodDocSus = impCodDocSus;
        }

        public String getImpNumDocSus() {
            return impNumDocSus;
        }

        public void setImpNumDocSus(String impNumDocSus) {
            this.impNumDocSus = impNumDocSus;
        }

        public String getImpFecDocSus() {
            return impFecDocSus;
        }

        public void setImpFecDocSus(String impFecDocSus) {
            this.impFecDocSus = impFecDocSus;
        }
    }

    public void setImpuestos(String impuestos) {
        this.impuestos = impuestos;
    }
    
//    public List<detalle> getDet() {
//        return det;
//    }
//
//    public void setDet(List<detalle> det) {
//        this.det = det;
//    }

    public String getAmbiente() {
        return ambiente;
    }

    public void setAmbiente(String ambiente) {
        this.ambiente = ambiente;
    }

    public String getTipoEmision() {
        return tipoEmision;
    }

    public void setTipoEmision(String tipoEmision) {
        this.tipoEmision = tipoEmision;
    }

    public String getRazonSocial() {
        return razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    public String getNombreComercial() {
        return nombreComercial;
    }

    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }

    public String getRuc() {
        return ruc;
    }

    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    public String getClaveAcceso() {
        return claveAcceso;
    }

    public void setClaveAcceso(String claveAcceso) {
        this.claveAcceso = claveAcceso;
    }

    public String getCodDoc() {
        return codDoc;
    }

    public void setCodDoc(String codDoc) {
        this.codDoc = codDoc;
    }

    public String getEstablecimiento() {
        return establecimiento;
    }

    public void setEstablecimiento(String establecimiento) {
        this.establecimiento = establecimiento;
    }

    public String getPuntoEmision() {
        return puntoEmision;
    }

    public void setPuntoEmision(String puntoEmision) {
        this.puntoEmision = puntoEmision;
    }

    public String getSecuencial() {
        return secuencial;
    }

    public void setSecuencial(String secuencial) {
        this.secuencial = secuencial;
    }

    public String getMatriz() {
        return Matriz;
    }

    public void setMatriz(String Matriz) {
        this.Matriz = Matriz;
    }

    public String getFecha() {
        return Fecha;
    }

    public void setFecha(String Fecha) {
        this.Fecha = Fecha;
    }

    public String getDireccion() {
        return Direccion;
    }

    public void setDireccion(String Direccion) {
        this.Direccion = Direccion;
    }

    public String getContribEsp() {
        return contribEsp;
    }

    public void setContribEsp(String contribEsp) {
        this.contribEsp = contribEsp;
    }

    public String getObligCont() {
        return obligCont;
    }

    public void setObligCont(String obligCont) {
        this.obligCont = obligCont;
    }

    public String getCliTipId() {
        return cliTipId;
    }

    public void setCliTipId(String cliTipId) {
        this.cliTipId = cliTipId;
    }

    public String getCliRazonSocial() {
        return cliRazonSocial;
    }

    public void setCliRazonSocial(String cliRazonSocial) {
        this.cliRazonSocial = cliRazonSocial;
    }

    public String getCliId() {
        return cliId;
    }

    public void setCliId(String cliId) {
        this.cliId = cliId;
    }

    public String getCliPerFiscal() {
        return cliPerFiscal;
    }

    public void setCliPerFiscal(String cliPerFiscal) {
        this.cliPerFiscal = cliPerFiscal;
    }

    public String getAdicional1() {
        return adicional1;
    }

    public void setAdicional1(String adicional1) {
        this.adicional1 = adicional1;
    }

    public String getAdicional2() {
        return adicional2;
    }

    public void setAdicional2(String adicional2) {
        this.adicional2 = adicional2;
    }

    public String getAdicional3() {
        return adicional3;
    }

    public void setAdicional3(String adicional3) {
        this.adicional3 = adicional3;
    }
}
